Add clarity on WG diversity
HSF/hsf.github.io pull request #1034
Opened 2021-12-08 10:39 UTC by graeme-a-stewart

We didn't say anywhere that converers from the same experiment is strongly discouraged, although we have always had this as a unwritten policy - so better that it is publically written down.

2021-12-08 16:11 UTC, hegner requested changes

2021-12-08 16:11 UTC, hegner commented on what_are_WGs.md
> +We strive for a diverse representation in the HSF working group and, in
"the groups" or "a group" ?

2021-12-08 16:15 UTC, graeme-a-stewart commented on what_are_WGs.md
> +We strive for a diverse representation in the HSF working group and, in
Yep, "groups" is better, thanks.

2021-12-09 15:09 UTC, graeme-a-stewart commented
Ping on this - I think it's good to go now.

2021-12-09 17:51 UTC, hegner approved these changes

2021-12-09 17:51 UTC, merged