Add Compiler-Research-CUDA-clang-repl proposal
HSF/hsf.github.io pull request #1087
Opened 2022-02-18 13:15 UTC by ioanaif

2022-02-19 12:29 UTC, hegner requested changes

2022-02-19 12:29 UTC, hegner commented on _gsocprojects/2022/project_Compiler-Research.md
> +  [Compiler-Research](https://compiler-reserch.org/) -  We are a group of programming languages enthusiasts located at Princeton University and CERN. Our primary goal is research into foundational so
Should be https://compiler-sesearch.org

2022-02-20 11:02 UTC, ioanaif commented on _gsocprojects/2022/project_Compiler-Research.md
> +  [Compiler-Research](https://compiler-reserch.org/) -  We are a group of programming languages enthusiasts located at Princeton University and CERN. Our primary goal is research into foundational so
Fixed. Thank you!

2022-02-20 16:04 UTC, hegner approved these changes

2022-02-20 16:04 UTC, merged