Add proposal for ACTS GPU R&D
HSF/hsf.github.io pull request #1093
Opened 2022-02-19 01:10 UTC by beomki-yeo

2022-02-20 18:47 UTC, cgleggett commented on _gsocproposals/2022/proposal_ACTS_GPU_pipeline_optimization.md
> +We are expected to observe the actual acceleration of GPU pipeline, especially for CUDA API.
increased throughput

2022-02-20 19:16 UTC, agheata requested changes

2022-02-20 19:16 UTC, agheata commented on _gsocproposals/2022/proposal_ACTS_GPU_pipeline_optimization.md
> +We are expected to observe the actual acceleration of GPU pipeline, especially for CUDA API.
This is very minimalistic as expected results. Please expand with more clear/measurable objectives. What kind of acceleration is expected? Benchmarking which use case? We are also encouraging stating here also what the student is expected to learn/achieve in this process.

2022-02-20 19:16 UTC, agheata commented on _gsocproposals/2022/proposal_ACTS_GPU_pipeline_optimization.md
> +for GPU acceleration by parallelizing the track reconstruction. vecmem is a memory management toolkit which provides
For readability, maybe emphasize or use quotes for `vecmem`, `detray` and `traccc` when they start a sentence.

2022-02-20 23:46 UTC, beomki-yeo commented on _gsocproposals/2022/proposal_ACTS_GPU_pipeline_optimization.md
> + * **[Beomki Yeo](mailto:beomki.yeo@berkeley.edu)** (LBNL)
I added @cgleggett

2022-02-21 09:02 UTC, agheata approved these changes

2022-02-21 09:06 UTC, agheata approved these changes

2022-02-21 09:06 UTC, agheata commented on _gsocproposals/2022/proposal_ACTS_GPU_pipeline_optimization.md
> + * [Charles Leggett](cgleggett@lbl.gov) (LBNL)
```suggestion
 * [Charles Leggett](mailto:cgleggett@lbl.gov) (LBNL)
```

2022-02-21 09:06 UTC, agheata commented on gsoc/2022/mentors.md
> +* Charles Leggett [cgleggett@lbl.gov] LBNL
```suggestion
* Charles Leggett [cgleggett@lbl.gov](mailto:cgleggett@lbl.gov) LBNL
```

2022-02-21 09:09 UTC, merged