Escape Repository as a Service Proposal
HSF/hsf.github.io pull request #1100
Opened 2022-02-21 16:57 UTC by garciagenrique

2022-02-21 20:13 UTC, agheata requested changes

2022-02-21 20:13 UTC, agheata commented on _gsocprojects/2022/project_ESCAPE-OSSR.md
> +---
```suggestion
---
summary: |
  Add a shorter description of one paragraph only

```

2022-02-21 20:13 UTC, agheata commented on _gsocproposals/2022/proposal_ESCAPE-repository-as-a-service.md
> +
It's recommended to add at least one sentence about what the student will learn.

2022-02-22 11:12 UTC, garciagenrique commented on _gsocproposals/2022/proposal_ESCAPE-repository-as-a-service.md
> +duration: 300
Right, thanks !

2022-02-22 11:15 UTC, garciagenrique commented
Thanks for the feedback @agheata !
Comments are implemented.

Setting temporarily the PR on draft (contacting HSF admins by email)

2022-02-22 19:09 UTC, garciagenrique commented
(I edited the previous message).

PR is ready for re-review. Thanks in advance :)

2022-02-22 19:59 UTC, agheata approved these changes

2022-02-22 19:59 UTC, merged

2022-02-23 17:06 UTC, garciagenrique commented
Hi @agheata,
I see that the Organization, project and proposal were not correctly deployed in the HSF page. Let me know if I can help anyhow.

2022-02-23 20:43 UTC, aflp91 commented
@garciagenrique: I opened a PR #1103 about this yesterday…

2022-02-23 21:46 UTC, garciagenrique commented
> @garciagenrique: I opened a PR #1103 about this yesterday…

Thanks a lot @aflp91, didn't got any notification.