Create Blog Report
HSF/hsf.github.io pull request #1181
Opened 2022-07-28 15:09 UTC by Harshalzzzzzzz

2022-08-01 11:41 UTC, agheata requested changes
Please fix the errors reported by the link checker. Also provide the missing link for PR 2 and ask your mentor(s) to review this.

2022-08-05 14:12 UTC, agheata commented
@Harshalzzzzzzz can you please make the requested changes to be able to merge this?

2022-08-05 14:16 UTC, Harshalzzzzzzz commented
> @Harshalzzzzzzz can you please make the requested changes to be able to merge this?

@agheata I have updated the link
I will ask my mentors to review this
Thank you !

2022-08-05 14:18 UTC, lmoneta approved these changes
It is fine for me

2022-08-05 14:29 UTC, agheata requested changes

2022-08-05 14:29 UTC, agheata commented on _gsocblogs/2022/blog_TMVADevelopments_HarshalShende.md
> + - [Project Proposal]([https://docs.google.com/presentation/d/15zMAqtXGF_JnOSiL8Pe5A9m1hezotmRIGW_Dgp9ZJHQ/edit#slide=id.p](https://docs.google.com/document/d/1Ss_nWnIUPxGdg4l5dX3RK5670iRZjSujFoIwUAk
This link is wrong, keep the actual link to the document with the format: `[Project Proposal](link)`

2022-08-05 14:30 UTC, agheata commented
> I have updated the link

There is still a wrongly formatted link, see above

2022-08-05 15:23 UTC, agheata approved these changes

2022-08-05 15:23 UTC, merged