GSoC 2022 student blog for ESCAPE - OSSR [mid term evaluation]
HSF/hsf.github.io pull request #1196
Opened 2022-08-04 09:17 UTC by sudersan01

2022-08-04 09:32 UTC, sudersan01 commented
This pull request contains the blog post for ESCAPE - OSSR for GSoC 2022 mid-term evaluation. 
mentored by @garciagenrique

2022-08-05 12:26 UTC, garciagenrique commented
@sudersan01 could not add me as a reviewer. Nevertheless, everything is OK from my side.

2022-08-05 14:10 UTC, agheata requested changes

2022-08-05 14:10 UTC, agheata commented on _gsocblogs/2022/blog_ESCAPE-OSSR_Sudersan.md
> +This blog entails my progress, learning and experience acquired during the GSoC period.
```suggestion
 This blog entails my progress, learning and experience acquired during the GSoC period.
```

2022-08-05 14:10 UTC, agheata commented on _gsocblogs/2022/blog_ESCAPE-OSSR_Sudersan.md
> +This blog entails my progress, learning and experience acquired during the GSoC period.
You need to add a space at least at the beginning of the intro to be interpreted correctly

2022-08-05 14:10 UTC, agheata commented on _gsocblogs/2022/blog_ESCAPE-OSSR_Sudersan.md
> +Project Repository - https://gitlab.in2p3.fr/escape2020/wp3/ossr-jupyterlab-extension <br />
```suggestion
Project [Repository](https://gitlab.in2p3.fr/escape2020/wp3/ossr-jupyterlab-extension) <br />
```

2022-08-05 14:10 UTC, agheata commented on _gsocblogs/2022/blog_ESCAPE-OSSR_Sudersan.md
> +Project Proposal - https://hepsoftwarefoundation.org/gsoc/2022/proposal_ESCAPE-repository-as-a-service.html
```suggestion
Project [Proposal](https://hepsoftwarefoundation.org/gsoc/2022/proposal_ESCAPE-repository-as-a-service.html)
```

2022-08-05 14:10 UTC, agheata commented on _gsocblogs/2022/blog_ESCAPE-OSSR_Sudersan.md
> +Project Proposal - https://hepsoftwarefoundation.org/gsoc/2022/proposal_ESCAPE-repository-as-a-service.html
Please add also links to your commits or pull requests in the project repo, as well as any other relevant material (like  links to meetings/presentations)

2022-08-05 17:19 UTC, sudersan01 commented
@agheata I have made the changes and updated the blog as specified. pls verify

2022-08-08 06:49 UTC, agheata approved these changes

2022-08-08 06:49 UTC, merged