Final blog
HSF/hsf.github.io pull request #1227
Opened 2022-08-30 18:52 UTC by Harshil-Jani

Adding the Final Version of the GSOC 2022 Blog for  Geant4 Performance Analysis and Data Vizualization Project.

2022-08-30 19:13 UTC, agheata commented on _gsocblogs/2022/blog_Geant4_HarshilJani.md
> +title: Community Bonding Period
```suggestion
title: Geant4 - Performance Data Visualization using d3.js 
```

2022-08-30 19:34 UTC, agheata reviewed
@Harshil-Jani the blog renders fine, except that the figures are too big, maybe try to scale them to the page width. I need an OK from one of your mentors before approving it.

2022-08-30 19:40 UTC, agheata commented
Otherwise, you have an unclean local merge mixing in commits that are not yours, I'm afraid you'll have to fetch the master, branch again, and make another PR.

2022-09-01 07:18 UTC, agheata requested changes
@Harshil-Jani please rebase your branch against the curret master

2022-09-01 08:49 UTC, amadio commented
Hi @Harshil-Jani Overall the contents looks ok, but there are still merge conflicts between your branch and upstream's master branch. You need to use `git reabse` to sync your branch with latest commits from upstream. The figures seem too big for the text, and there are capitalized words in the middle of sentences that need to be fixed. Please try to pass the text through a proofreading software to help catch other typos as well. Then you can push again and tag me to go through a next round of review.

2022-09-02 06:48 UTC, agheata commented
@amadio is this OK with you? Capitalization seems to be more a matter of style, I have no problem with that. The page and figures render fine now.

2022-09-02 07:01 UTC, agheata approved these changes

2022-09-02 07:01 UTC, merged