Midterm blog by SanchiMittal
HSF/hsf.github.io pull request #1229
Opened 2022-09-02 13:11 UTC by SanchiMittal

Midterm blog added.

cc @lmoneta

2022-09-02 13:21 UTC, sanjibansg approved these changes

2022-09-02 19:02 UTC, agheata requested changes
@SanchiMittal please adopt the changes I suggested

2022-09-02 19:02 UTC, agheata commented on _gsocblogs/2022/blog_ROOT_SanchiMittal.md
> +photo: images/blog_authors/SanchiMittal.jpeg
```suggestion
photo: blog_authors/SanchiMittal.jpeg 
```

2022-09-02 19:02 UTC, agheata commented on _gsocblogs/2022/blog_ROOT_SanchiMittal.md
> +![CERN-HSF-GSoC-logo](https://hepsoftwarefoundation.org/images/CERN-HSF-GSoC-logo.png)
```suggestion
![CERN]({{ site.baseurl }}/images/CERN-HSF-GSoC-logo.png){:height="100px"} Google Summer of Code 2022
```

2022-09-03 02:32 UTC, SanchiMittal commented
Thank you for the review! I have updated the PR with requested changes.

2022-09-03 08:42 UTC, agheata approved these changes

2022-09-03 08:43 UTC, merged