Updated blog for post mid-term evaluation period
HSF/hsf.github.io pull request #1249
Opened 2022-09-13 18:03 UTC by waridrox

Here's the updated blog post, also incorporating mid-term evaluation period. Originally first published at [medium](https://medium.com/@waridrox/gsoc-2022-final-project-report-c206883936fa).

2022-09-15 13:25 UTC, glpatcern requested changes
Thanks @waridrox, a few more suggestions follow

2022-09-15 13:25 UTC, glpatcern commented on _gsocblogs/2022/blog_EtherpadPlugin_MohammadWarid.md
> +The main goal for the project was an in-app workflow, targeted to onboard new users over the etherpad each possessing a unique ID. This was achieved by fetching query parameters from a custom `/setEF
On top of what Andrei asked, please change `in-app` into `open file in app`, and then I suggest `targeted to enable users of a cloud storage opening and working with their files into Etherpad`.

2022-09-15 13:25 UTC, glpatcern commented on _gsocblogs/2022/blog_EtherpadPlugin_MohammadWarid.md
> +The `padUpdate` event in etherpad is supposed to fire on every new change to the etherpad. This is more noticeable when dealing with every keystroke event. To lower the amount of `pending 202` reques
Let's simplify `To lower the amount of pending requests` into `To lower the amount of requests` - As you know the wopiserver is performing its own "debouncing" and that's the reason it responds with 202.

2022-09-15 18:49 UTC, waridrox commented
Done!

2022-09-17 08:15 UTC, glpatcern commented
For me it's good to go, @agheata you can merge if you wish!

2022-09-19 07:10 UTC, agheata approved these changes

2022-09-19 07:10 UTC, merged