GSOC'22- Root Project- Final Evaluation Blog for Inference Project
HSF/hsf.github.io pull request #1258
Opened 2022-09-24 18:46 UTC by Neel-Shah-29

- The Blog has all the details of my work done during GSOC 2022 at CERN HSF(Root Project). 
- My project was ROOT - TMVA SOFIE Developments - Inference Code Generation for Deep Learning models.
- The deadline for the final evaluation is 10th October,2022.

2022-09-24 19:00 UTC, Neel-Shah-29 commented
Hello @lmoneta, Kindly review the  blog for the final evaluation. Please let me know if any improvements are required. Thanks!

2022-09-26 07:39 UTC, agheata commented
@lmoneta we need your approval before merging

2022-10-04 08:47 UTC, lmoneta approved these changes
Nice blog !
Thank you @Neel-Shah-29 !

2022-10-04 12:21 UTC, agheata requested changes
Formatting changes that I will apply

2022-10-04 12:21 UTC, agheata commented on _gsocblogs/2022/blog_ROOT_Neelshah.md
>  1) [Python Tutorials for various C files of Tutorials/TMVA](https://gist.github.com/Neel-Shah-29/7e46bee55f7c09a18e94696a0a3e5ccf)
```suggestion
1) [Python Tutorials for various C files of Tutorials/TMVA](https://gist.github.com/Neel-Shah-29/7e46bee55f7c09a18e94696a0a3e5ccf)

```

2022-10-04 12:21 UTC, agheata commented on _gsocblogs/2022/blog_ROOT_Neelshah.md
>  2) [Documentation on RModelParser_ONNX.cxx](https://gist.github.com/Neel-Shah-29/5c1399ccd23903928128822c6f3e0957)
```suggestion
2) [Documentation on RModelParser_ONNX.cxx](https://gist.github.com/Neel-Shah-29/5c1399ccd23903928128822c6f3e0957)

```

2022-10-04 12:21 UTC, agheata commented on _gsocblogs/2022/blog_ROOT_Neelshah.md
>  3) [Getting into GSOC 2022](https://gist.github.com/Neel-Shah-29/3f04f05a8a353605068e32e55a5093c1)
```suggestion
3) [Getting into GSOC 2022](https://gist.github.com/Neel-Shah-29/3f04f05a8a353605068e32e55a5093c1)

```

2022-10-04 12:21 UTC, agheata commented on _gsocblogs/2022/blog_ROOT_Neelshah.md
>  4) [All about Community Bonding Period](https://gist.github.com/Neel-Shah-29/b2c887adaa118ba68b42e324d3b2a47a)
```suggestion
4) [All about Community Bonding Period](https://gist.github.com/Neel-Shah-29/b2c887adaa118ba68b42e324d3b2a47a)

```

2022-10-04 12:21 UTC, agheata commented on _gsocblogs/2022/blog_ROOT_Neelshah.md
>  5) [Implementing the Operators in Sofie](https://gist.github.com/Neel-Shah-29/f0371566ca1e24a6b3a9b4097cdd44db)
```suggestion
5) [Implementing the Operators in Sofie](https://gist.github.com/Neel-Shah-29/f0371566ca1e24a6b3a9b4097cdd44db)

```

2022-10-04 12:21 UTC, agheata commented on _gsocblogs/2022/blog_ROOT_Neelshah.md
> +6) [Final Evaluation Detailed Report](https://gist.github.com/Neel-Shah-29/d51a9038dd07ef096127a62a92113fa0)
```suggestion
6) [Final Evaluation Detailed Report](https://gist.github.com/Neel-Shah-29/d51a9038dd07ef096127a62a92113fa0)

```

2022-10-04 12:21 UTC, agheata commented on _gsocblogs/2022/blog_ROOT_Neelshah.md
> +7) [Final Project Presentation](https://docs.google.com/presentation/d/1VdOEkNsFcaBAo15kjVDRtJ_BWvVh9E6KgKzzrmkr1NQ/edit?usp=sharing)
```suggestion
7) [Final Project Presentation](https://docs.google.com/presentation/d/1VdOEkNsFcaBAo15kjVDRtJ_BWvVh9E6KgKzzrmkr1NQ/edit?usp=sharing)

```

2022-10-04 12:21 UTC, agheata commented on _gsocblogs/2022/blog_ROOT_Neelshah.md
> +8) [GSOC Project Page](https://summerofcode.withgoogle.com/programs/2022/projects/vEuHzl6G)
```suggestion
8) [GSOC Project Page](https://summerofcode.withgoogle.com/programs/2022/projects/vEuHzl6G)

```

2022-10-04 12:21 UTC, agheata commented on _gsocblogs/2022/blog_ROOT_Neelshah.md
>  ## Proposal Link \: [Inference Code Generation for Deep Learning models](https://docs.google.com/document/d/1tvTY9Rq5j0XW8KFfvkWHWlmE__-94h-Nj0tCkMjYnzs/edit?usp=sharing)
```suggestion
## Proposal Link \: 
[Inference Code Generation for Deep Learning models](https://docs.google.com/document/d/1tvTY9Rq5j0XW8KFfvkWHWlmE__-94h-Nj0tCkMjYnzs/edit?usp=sharing)
```

2022-10-04 12:22 UTC, agheata approved these changes

2022-10-04 12:25 UTC, merged