Final evaluation - blog_post
HSF/hsf.github.io pull request #1273
Opened 2022-10-09 21:51 UTC by luozf14

This pull request contains the blog post for the GSoC final evaluation of the project
"Automatic conversion of data stored in TTree form to RNTuple", mentored by @jalopezg-r00t .

Waiting approval of @agheata or @hegner .

2022-10-10 12:48 UTC, jalopezg-r00t approved these changes
LGTM, just a minor change suggestion.

2022-10-10 12:48 UTC, jalopezg-r00t commented on _gsocblogs/2022/blog_ROOT_ZifengLuo.md
> +      <td rowspan="5">Completed. All types are one-to-one mapped except types that are not supported by RNTuple I/O. For example, <code>std::set&lt;T></code> will cause program crash. However, conver
```suggestion
      <td rowspan="5">Completed. All types are one-to-one mapped except types that are not supported by RNTuple I/O. For example, <code>std::set&lt;T></code> will not work. However, conversion of TTree containing branches of <code>ROOT::RVec&lt;T></code> is not stable in current stage (see section <b>Known issues and Future work</b>).</td>
```
We could actually handle the exception thrown in `RFieldBase::Create()`, but that is beyond the GSoC project goals.

2022-10-12 20:47 UTC, agheata requested changes

2022-10-12 20:47 UTC, agheata commented on _gsocblogs/2022/blog_ROOT_ZifengLuo.md
> +photo: blog_authors/ZifengLuo.jpg
```suggestion
photo: blog_authors/ZifengLuo.jpeg
```

2022-10-12 20:49 UTC, agheata approved these changes

2022-10-12 20:50 UTC, merged