Update Nimish's Endterm GSoC Blog Post
HSF/hsf.github.io pull request #1280
Opened 2022-10-21 20:54 UTC by nimishbongale

2022-10-24 08:34 UTC, agheata requested changes
@nimishbongale, please take the suggestions into account and ask your mentors to comment/approve your PR

2022-10-24 08:34 UTC, agheata commented on _gsocblogs/2022/blog_Rucio_NimishBongale.md
>  ### Project Proposal link: [https://summerofcode.withgoogle.com/programs/2022/projects/1ps6wuOz](https://summerofcode.withgoogle.com/programs/2022/projects/1ps6wuOz)
Please don't use explicit links, in particular in subtitles
```suggestion
[Project Proposal](https://summerofcode.withgoogle.com/programs/2022/projects/1ps6wuOz)
```

2022-10-24 08:34 UTC, agheata commented on _gsocblogs/2022/blog_Rucio_NimishBongale.md
>  ### Live storybook deployment: [https://rucio.cern.ch/webui](https://rucio.cern.ch/webui)
```suggestion
[Live storybook deployment](https://rucio.cern.ch/webui)
```

2022-10-24 08:34 UTC, agheata commented on _gsocblogs/2022/blog_Rucio_NimishBongale.md
> +![Login](https://raw.githubusercontent.com/nimishbongale/webui/feature-add-snapshots/public/Login.png)
All your figures are too big and need to be scaled to 100% width as below:
```suggestion
<img src="https://raw.githubusercontent.com/nimishbongale/webui/feature-add-snapshots/public/Login.png" alt="Login" width="100%">
```

2022-10-24 08:34 UTC, agheata commented on _gsocblogs/2022/blog_Rucio_NimishBongale.md
> +![DID Metadata](https://raw.githubusercontent.com/nimishbongale/webui/feature-add-snapshots/public/DIDMetadata.png)
see above

2022-10-24 08:34 UTC, agheata commented on _gsocblogs/2022/blog_Rucio_NimishBongale.md
> +![Rule Metadata](https://raw.githubusercontent.com/nimishbongale/webui/feature-add-snapshots/public/RuleMetadata.png)
see above

2022-10-24 08:34 UTC, agheata commented on _gsocblogs/2022/blog_Rucio_NimishBongale.md
> +![List Rules](https://raw.githubusercontent.com/nimishbongale/webui/feature-add-snapshots/public/ListRules.png)
see above

2022-10-24 08:34 UTC, agheata commented on _gsocblogs/2022/blog_Rucio_NimishBongale.md
> +![Step 4](https://raw.githubusercontent.com/nimishbongale/webui/feature-add-snapshots/public/Step4.png)
see above for figures

2022-10-24 08:34 UTC, agheata commented on _gsocblogs/2022/blog_Rucio_NimishBongale.md
> +![Search](https://raw.githubusercontent.com/nimishbongale/webui/feature-add-snapshots/public/Search.png)
see above

2022-10-24 08:34 UTC, agheata commented on _gsocblogs/2022/blog_Rucio_NimishBongale.md
> +![Error Boundary](https://raw.githubusercontent.com/nimishbongale/webui/feature-add-snapshots/public/ErrorBoundary.png)
see above

2022-10-24 08:34 UTC, agheata commented on _gsocblogs/2022/blog_Rucio_NimishBongale.md
> +![Storybook](https://raw.githubusercontent.com/nimishbongale/webui/feature-add-snapshots/public/Storybook.png)
see above

2022-10-24 08:34 UTC, agheata commented on _gsocblogs/2022/blog_Rucio_NimishBongale.md
> +#98 by [nimishbongale](https://github.com/rucio/webui/issues?q=is%3Apr+author%3Animishbongale) was merged 4 days ago
Please remove all the lines like this showing the status of the PR, just keep the links to the PRs

2022-10-24 13:27 UTC, agheata commented
Looks good to me, waiting for one of your mentors' OK before merging

2022-10-24 13:37 UTC, nimishbongale commented
@maany @bari12

Please do review/approve the same, thank you! 😄

2022-10-25 08:56 UTC, maany requested changes
Well done @nimishbongale. It is a pretty extensive and exhaustive report. I have left some minor comments

2022-10-25 08:56 UTC, maany commented on _gsocblogs/2022/blog_Rucio_NimishBongale.md
> +Central to the functionality of the Rucio WebUI is the ability to create rules with just a few clicks.Once a rule is created, the rule automatically reflects in the List Rules page, owing to the impl
We should also credit Valentina for laying the foundations of the error and rule workflow pages and the corresponding storybook components ;). You must mention here the work you have done on top to refactor it to the new architecture and clean up the UI to make it fit more with the rest of the components

2022-10-25 08:56 UTC, maany commented on _gsocblogs/2022/blog_Rucio_NimishBongale.md
> +The Login page serves as the entry point to the entire application. It makes use of the custom built Form component, which supports field validation. It handles multiple auth mechanisms such as Usern
You could also mention some of the challenges with OIDC, PKCE and x509 strategies somewhere in this document.

2022-10-25 08:56 UTC, maany commented on _gsocblogs/2022/blog_Rucio_NimishBongale.md
> +- While the GSoC period ends here, contributing to OSS should continue!
Maybe you could also add a section to summarize the pending tasks and what could be improved :)

2022-10-26 15:04 UTC, maany approved these changes
Looks good, could you use her github handle [elizabethh777](https://github.com/elizabethh777)

2022-10-26 15:20 UTC, nimishbongale commented
> Looks good, could you use her github handle [elizabethh777](https://github.com/elizabethh777)

Done!

2022-10-26 15:22 UTC, maany approved these changes
Looks good to go!

2022-10-27 08:55 UTC, agheata approved these changes

2022-10-27 08:55 UTC, merged