Final blog update for Belle II project
HSF/hsf.github.io pull request #1281
Opened 2022-10-23 11:34 UTC by alexverus

Update includes progress made post mid term, along with some concluding sections, screen-grabs and links to pull requests.

2022-10-23 12:12 UTC, alexverus commented
Requesting for review from @hegner @agheata
My supervisor (@tkuhr) was unable to post comments here

2022-10-24 08:03 UTC, agheata requested changes
@alexverus the branch needs to be rebased on the current master. Please ask your mentor to confirm that he is OK with your blog (if unable to comment in the PR, just by mail to the admin list)

2022-10-24 08:58 UTC, tkuhr commented
The blog correctly describes Arul's achievements. I approve it.

2022-10-24 09:21 UTC, hegner commented
@tkuhr - thanks for the quick reaction.

2022-10-24 10:30 UTC, alexverus commented
@agheata from what I can see, my branch doesn't seem to be behind upstream:master, apart from these commits. Could you kindly help me verify this?

2022-10-24 11:35 UTC, agheata commented
> @agheata from what I can see, my branch doesn't seem to be behind upstream:master, apart from these commits. Could you kindly help me verify this?

If I do `gh pr checkout 1281` after fetching the upstream and rebasing my master on upstream/master, I get an error:
```
From https://github.com/HSF/hsf.github.io
 ! [rejected]        refs/pull/1281/head -> alexverus/master  (non-fast-forward)
exit status 1
```
Try to do on your local master:
```
git fetch upstream
git rebase upstream/master
git push [-f] # use -f if a simple push fails and proposes you a pull first
```

2022-10-24 15:23 UTC, alexverus commented
> Try to do on your local master:

I had tried this earlier, and tried it again now and received `Everything up-to-date`. When I attempt `git diff master..upstream/master` I can see only one file changed(my blog post), and also on the web I see that there are no merge conflicts:
![merge](https://user-images.githubusercontent.com/19401461/197562069-58cef9a0-9e89-4050-8822-df67fd5735d1.PNG)

I found that there's an open [issue](https://github.com/cli/cli/issues/562) with `gh pr checkout`, could it be possibly related to that? I could be doing something wrong too, haven't yet found out what though. Should I just close this and open a new request?

Apologies for the inconvenience.

2022-10-25 07:16 UTC, agheata reviewed
You were right, there is a bug in gh. There are just few subsection #### indenting problems, fixing them via the web interface.

2022-10-25 07:16 UTC, agheata commented on _gsocblogs/2022/blog_Belle2_ArulPrakash.md
> + #### CherrPy meets GitLab
```suggestion
#### CherrPy meets GitLab
```

2022-10-25 07:16 UTC, agheata commented on _gsocblogs/2022/blog_Belle2_ArulPrakash.md
> + #### Plot/logfile endpoints
```suggestion
#### Plot/logfile endpoints
```

2022-10-25 07:16 UTC, agheata commented on _gsocblogs/2022/blog_Belle2_ArulPrakash.md
> + #### Consolidate and display datafiles
```suggestion
#### Consolidate and display datafiles
```

2022-10-25 07:16 UTC, agheata commented on _gsocblogs/2022/blog_Belle2_ArulPrakash.md
>   #### Code review
```suggestion
#### Code review 
```

2022-10-25 07:16 UTC, agheata commented on _gsocblogs/2022/blog_Belle2_ArulPrakash.md
>   #### Local base
```suggestion
#### Local base
```

2022-10-25 07:18 UTC, agheata approved these changes

2022-10-25 07:19 UTC, merged

2022-10-25 16:35 UTC, alexverus commented
Thanks for the quick review and support @agheata @hegner @tkuhr