Change Kilian's affiliation
HSF/hsf.github.io pull request #1309
Opened 2022-12-06 10:52 UTC by hegner

#1305

2022-12-06 16:01 UTC, klieret commented
Thanks! 

Not sure why the link checker is still failing, probably fine after merging?

2022-12-06 16:01 UTC, klieret approved these changes

2022-12-06 17:35 UTC, graeme-a-stewart requested changes

2022-12-06 17:36 UTC, graeme-a-stewart commented
> Thanks!
> 
> Not sure why the link checker is still failing, probably fine after merging?

I think perhaps the wrong URL was "fixed"?

2022-12-06 23:24 UTC, klieret commented
I recently removed the `howto-new-module` in #1306 , but as part of that gripped for `howto-new-module` on `master`. It doesn't show anything anymore. 

I conclude that this PR is probably based on an earlier version without that change and things will be fine after we merge.

2022-12-07 07:42 UTC, graeme-a-stewart approved these changes

2022-12-07 07:42 UTC, merged