[WIP] Julia-bindings proposal
HSF/hsf.github.io pull request #1340
Opened 2023-02-06 16:54 UTC by peremato

2023-02-06 17:16 UTC, vvolkl requested changes
Thanks Pere - just some minor fixes to make sure jekyll renders this correctly.

I think you'll also need to rename `_gsocproposals/2023/proposal_Julia-HEP-C++.md` to `_gsocproposals/2023/proposal_Julia-HEP-Cpp.md` for the file to be recognised.

2023-02-06 17:16 UTC, vvolkl commented on _gsocorgs/2023/cea-irfu.md
> +The [IRFU](https://irfu.cea.fr), Institute for Research on the fundamental laws of the universe, of the Fundamental Research Division of the [CEA](https://www.cea.fr), brings together three scientifi
```suggestion
  The [IRFU](https://irfu.cea.fr), Institute for Research on the fundamental laws of the universe, of the Fundamental Research Division of the [CEA](https://www.cea.fr), brings together three scientific disciplines, astrophysics, nuclear physics and particle physics, as well as al the associated technological expertise.
```

2023-02-06 17:16 UTC, vvolkl commented on _gsocprojects/2023/project_HSF.md
> +  solve current problems in particle physics.
```suggestion
    The HEP Software Foundation encourages cooperation and common development of software in High Energy Physics. The HSF hosts a number of software projects where developers are working to solve current problems in particle physics.
```

2023-02-06 17:43 UTC, peremato commented
@vvolkl if you are happy with it, can be merged.

2023-02-07 07:34 UTC, hegner approved these changes

2023-02-07 07:35 UTC, hegner commented
I did a minor fix myself but otherwise fine. Thanks!

2023-02-07 07:35 UTC, merged