Charing guide
HSF/hsf.github.io pull request #1548
Opened 2024-04-18 10:34 UTC by graeme-a-stewart

Add a HOWTO guide for chairing coordination meetings, so that new people know what to do

2024-04-18 10:38 UTC, hegner requested changes

2024-04-18 10:38 UTC, hegner commented on organization/running-meetings.md
> +title: "Charing an HSF Coordination Meeting"
missing an "i" in Chairing

2024-04-18 11:59 UTC, hegner approved these changes

2024-04-18 12:13 UTC, merged

2024-04-19 08:36 UTC, eduardo-rodrigues commented
Hi @graeme-a-stewart, I joined the fun too late as I was on holidays. This is now merged. I had a read, reads great, very nice addition, thanks 👍!