Add minutes for coordination meeting #276 (2024-10-10)
HSF/hsf.github.io pull request #1603
Opened 2024-10-10 15:48 UTC by jouvin

2024-10-10 15:52 UTC, jouvin commented
I asked Data Analysis conveners if they wanted to add something about their activity before we publish these minutes... Let's wait up to tomorrow (Friday)...

2024-10-14 07:41 UTC, graeme-a-stewart commented on organization/_posts/2024/2024-10-10-coordination.md
> +- Next meeting on Oct 28: https://indico.cern.ch/event/1461088/
Same minor issue - the links need to be embedded in `<>`s

2024-10-14 07:41 UTC, graeme-a-stewart requested changes
Minor link formatting update

2024-10-14 07:41 UTC, graeme-a-stewart commented on organization/_posts/2024/2024-10-10-coordination.md
> +  - focused on Scipp (https://scipp.github.io/) and ragged data.
Ditto

2024-10-14 10:28 UTC, graeme-a-stewart commented
I'm going to accept this one and just patch in the minor changes, because it would be useful to have the minutes published for an email that needs sent.

2024-10-14 10:28 UTC, graeme-a-stewart approved these changes

2024-10-14 10:28 UTC, merged