Add Isaac Morales blog
HSF/hsf.github.io pull request #1606
Opened 2024-10-20 14:20 UTC by imorlxs

2024-10-22 12:22 UTC, vvolkl commented
Very nice, thanks! Giving @vgvassilev @LukasBreitwieser a chance to comment before merging

2024-10-23 10:48 UTC, vgvassilev approved these changes
Lgtm!

2024-10-23 11:37 UTC, LukasBreitwieser requested changes
Hi @imorlxs ,
Thank you very much for your work and blog. I left a few comments to strengthen the text. Let me know if you have any questions.
Best,
Lukas

2024-10-27 09:48 UTC, imorlxs commented on _gsocblogs/2024/blog_BioDynaMo_IsaacMorales.md
> +Looking ahead, further optimizations are planned, including potential module-based optimizations for BioDynaMo’s
For now we are generating one big module (biodynamo.pcm). The goal is to split that into smaller ones to load them on-demand.

2024-11-06 08:21 UTC, LukasBreitwieser approved these changes

2024-11-06 08:37 UTC, vvolkl approved these changes

2024-11-06 08:37 UTC, merged