CERNBox proposals
HSF/hsf.github.io pull request #888
Opened 2021-02-03 10:55 UTC by labkode

2021-02-03 17:04 UTC, aflp91 requested changes

2021-02-04 12:55 UTC, labkode commented on _gsocproposals/2021/proposal_scientific-notebook-ocis.md
> +title: Runtime plugin ecosystem support for OCIS
Nice spot!

2021-02-08 14:22 UTC, agheata commented on _gsocproposals/2021/proposal_runtime-plugin-ocis.md
> +* [XYZ](mailto:xyz@test.com) AARNet
Don't forget to add a mentor or remove this line.

2021-02-09 08:26 UTC, labkode commented
@agheata @aflp91 ready to be merged

2021-02-09 08:28 UTC, agheata approved these changes

2021-02-09 12:20 UTC, xvallspl approved these changes

2021-02-09 12:39 UTC, aflp91 approved these changes

2021-02-09 12:44 UTC, merged