[gsoc] Add PODIO proposal
HSF/hsf.github.io pull request #914
Opened 2021-02-16 15:32 UTC by jblomer

Draft proposal for the PODIO/RNTuple connection. Thomas and Valentin should approve before merging.

2021-02-16 15:37 UTC, xvallspl requested changes
Valentin and Thomas are not in mentors.md

2021-02-16 15:42 UTC, jblomer commented
Thanks! Added.

2021-02-16 16:03 UTC, aflp91 approved these changes
OK with me!

2021-02-16 17:54 UTC, agheata approved these changes

2021-02-16 17:59 UTC, tmadlener requested changes
Email addresses need to be updated to reflect the mentors here.

2021-02-16 17:59 UTC, tmadlener commented on _gsocproposals/2021/proposal_podio.md
> +Interested students please contact Jakob (jblomer@cern.ch) or Javier (j.lopez@cern.ch) for a warm-up and evaluation task.
```suggestion
Interested students please contact Jakob (jblomer@cern.ch), Valentin (valentin.volkl@cern.ch) or Thomas (thomas.madlener@desy.de) for a warm-up and evaluation task.
```

2021-02-16 17:59 UTC, tmadlener commented on _gsocproposals/2021/proposal_podio.md
> +PODIO translates such high-level object hierarchies into vectors of plain-old-data (POD) data structures for optimal I/O performance.
```suggestion
PODIO offers automatic code generation for efficiently implementing the EDM starting from a high level description of the objects.
PODIO uses plain-old-data (POD) structures to store the data of the objects and translates hierarchies of objects into vector of PODs for optimal I/O performance.
```

2021-02-16 17:59 UTC, tmadlener commented on _gsocproposals/2021/proposal_podio.md
> +PODIO translates such high-level object hierarchies into vectors of plain-old-data (POD) data structures for optimal I/O performance.
Just to mention that there is a code generation step somewhere in PODIO.

2021-02-18 09:53 UTC, agheata commented
@jblomer thanks for addressing the open discussions. If you need also a review from Valentin you should ping him.

2021-02-18 10:03 UTC, vvolkl approved these changes

2021-02-18 10:06 UTC, tmadlener approved these changes
Thanks for preparing this.

2021-02-18 13:25 UTC, merged