clad and cmssw proposals
HSF/hsf.github.io pull request #915
Opened 2021-02-17 13:24 UTC by davidlange6

2021-02-17 14:34 UTC, aflp91 requested changes
Two minor typos; otherwise looks OK with me.

2021-02-17 14:34 UTC, aflp91 commented on _gsocproposals/2021/proposal_functor_clad.md
> +The goal of this project is to modify Clad to handle suhc cases.
suhc => such

2021-02-17 14:34 UTC, aflp91 commented on _gsocproposals/2021/proposal_secondorder_clad.md
> +TFormula is a ROOT class which bridges compiled and interpreted code. Teach TFormula to use second order derivatives (using clad::hessian). The implementation should very similar to what was done in
should very similar => should be very similar ?

2021-02-17 14:35 UTC, xvallspl approved these changes

2021-02-17 14:37 UTC, xvallspl commented
see the changes suggested by Antoine

2021-02-17 16:31 UTC, agheata approved these changes

2021-02-18 10:10 UTC, aflp91 approved these changes
OK with me!

2021-02-18 10:55 UTC, merged