Add zfit lineshape proposal
HSF/hsf.github.io pull request #926
Opened 2021-02-20 14:48 UTC by mayou36

2021-02-21 17:02 UTC, agheata requested changes

2021-02-21 17:02 UTC, agheata commented on _gsocproposals/2021/proposal_zfit_lineshape
> +  * [Jonas Eschle](mailto:Jonas.Eschle@cern.ch)
The main mentor has to be in **bold**. You have to add a backup mentor (or more, but at least one). All mentors have to appear in gsoc/2021/mentors.md

2021-02-21 17:02 UTC, agheata commented on _gsocproposals/2021/proposal_zfit_lineshape
> +organization: University of Zurich
There are examples in that folder. Don't forget to add the logo file for the organization.

2021-02-22 14:32 UTC, mayou36 commented on _gsocproposals/2021/proposal_zfit_lineshape
> +organization: University of Zurich
I've re-used an older org file and called the org "UZH", I assume it's fine?

2021-02-22 14:33 UTC, mayou36 commented on _gsocproposals/2021/proposal_zfit_lineshape
> +  * [Jonas Eschle](mailto:Jonas.Eschle@cern.ch)
Added Rafael

2021-02-22 14:35 UTC, mayou36 commented on _gsocproposals/2021/proposal_zfit_lineshape
> +  * [Jonas Eschle](mailto:Jonas.Eschle@cern.ch)
Also added to the mentors

2021-02-22 14:42 UTC, agheata commented on _gsocproposals/2021/proposal_zfit_lineshape
> +organization: University of Zurich
Yes

2021-02-22 14:45 UTC, agheata requested changes

2021-02-22 14:45 UTC, agheata commented on _gsocproposals/2021/proposal_zfit_lineshape.md
> +  * **[Jonas Eschle](mailto:Jonas.Eschle@cern.ch)**
Only the main mentor in bold, please. We need only one responsible, for the evaluations, but we'll keep all mentors in the loop.

2021-02-22 14:45 UTC, agheata commented on gsoc/2021/mentors.md
> +* Rafael Silva Coutinho [Rafael Silva Coutinho](mailto:rafael.silva.coutinho@cern.ch) UZH
Insert sorted by last name in the list

2021-02-22 14:55 UTC, mayou36 commented
Okay done everything. Sorry for the trivial mistakes, I fixed them before but committed to the wrong branch...

2021-02-22 14:59 UTC, agheata approved these changes

2021-02-22 14:59 UTC, merged